{ id: 'Phaser.Tilemaps.Tileset()',
    longname: 'Phaser.Tilemaps.Tileset',
    name: 'Tileset',
    kind: 'constructor',
    memberof: 'Phaser.Tilemaps.Tileset',
    params:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    thisvalue: undefined,
    order: 2 },
  { id: 'Class',
    longname: 'Class',
    name: 'Class',
    kind: 'member',
    scope: 'global',
    params: [],
    thisvalue: undefined,
    copyright: '2018 Photon Storm Ltd.',
    author: [ 'Richard Davey <rich@photonstorm.com>' ],
    license: '{@link https://github.com/photonstorm/phaser/blob/master/license.txt|MIT License}',
    meta:
     { lineno: 7,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 0 },
  { id: 'Phaser.Tilemaps.Tileset#name',
    longname: 'Phaser.Tilemaps.Tileset#name',
    name: 'name',
    kind: 'member',
    scope: 'instance',
    description: 'The name of the Tileset.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 43,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 3 },
  { id: 'Phaser.Tilemaps.Tileset#firstgid',
    longname: 'Phaser.Tilemaps.Tileset#firstgid',
    name: 'firstgid',
    kind: 'member',
    scope: 'instance',
    description: 'The starting index of the first tile index this Tileset contains.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 52,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 4 },
  { id: 'Phaser.Tilemaps.Tileset#tileWidth',
    longname: 'Phaser.Tilemaps.Tileset#tileWidth',
    name: 'tileWidth',
    kind: 'member',
    scope: 'instance',
    description: 'The width of each tile (in pixels). Use setTileSize to change.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 61,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 5 },
  { id: 'Phaser.Tilemaps.Tileset#tileHeight',
    longname: 'Phaser.Tilemaps.Tileset#tileHeight',
    name: 'tileHeight',
    kind: 'member',
    scope: 'instance',
    description: 'The height of each tile (in pixels). Use setTileSize to change.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 71,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 6 },
  { id: 'Phaser.Tilemaps.Tileset#tileMargin',
    longname: 'Phaser.Tilemaps.Tileset#tileMargin',
    name: 'tileMargin',
    kind: 'member',
    scope: 'instance',
    description: 'The margin around the tiles in the sheet (in pixels). Use `setSpacing` to change.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 81,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 7 },
  { id: 'Phaser.Tilemaps.Tileset#tileSpacing',
    longname: 'Phaser.Tilemaps.Tileset#tileSpacing',
    name: 'tileSpacing',
    kind: 'member',
    scope: 'instance',
    description: 'The spacing between each the tile in the sheet (in pixels). Use `setSpacing` to change.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 91,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 8 },
  { id: 'Phaser.Tilemaps.Tileset#tileProperties',
    longname: 'Phaser.Tilemaps.Tileset#tileProperties',
    name: 'tileProperties',
    kind: 'member',
    scope: 'instance',
    description: 'Tileset-specific properties per tile that are typically defined in the Tiled editor in the\nTileset editor.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 101,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 9 },
  { id: 'Phaser.Tilemaps.Tileset#tileData',
    longname: 'Phaser.Tilemaps.Tileset#tileData',
    name: 'tileData',
    kind: 'member',
    scope: 'instance',
    description: 'Tileset-specific data per tile that are typically defined in the Tiled editor, e.g. within\nthe Tileset collision editor. This is where collision objects and terrain are stored.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 111,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 10 },
  { id: 'Phaser.Tilemaps.Tileset#image',
    longname: 'Phaser.Tilemaps.Tileset#image',
    name: 'image',
    kind: 'member',
    scope: 'instance',
    description: 'The cached image that contains the individual tiles. Use setImage to set.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 121,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 11 },
  { id: 'Phaser.Tilemaps.Tileset#rows',
    longname: 'Phaser.Tilemaps.Tileset#rows',
    name: 'rows',
    kind: 'member',
    scope: 'instance',
    description: 'The number of tile rows in the the tileset.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 131,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 12 },
  { id: 'Phaser.Tilemaps.Tileset#columns',
    longname: 'Phaser.Tilemaps.Tileset#columns',
    name: 'columns',
    kind: 'member',
    scope: 'instance',
    description: 'The number of tile columns in the tileset.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 141,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 13 },
  { id: 'Phaser.Tilemaps.Tileset#total',
    longname: 'Phaser.Tilemaps.Tileset#total',
    name: 'total',
    kind: 'member',
    scope: 'instance',
    description: 'The total number of tiles in the tileset.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 151,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 14 },
  { id: 'Phaser.Tilemaps.Tileset#texCoordinates',
    longname: 'Phaser.Tilemaps.Tileset#texCoordinates',
    name: 'texCoordinates',
    kind: 'member',
    scope: 'instance',
    description: 'The look-up table to specific tile image texture coordinates (UV in pixels). Each element\ncontains the coordinates for a tile in an object of the form {x, y}.',
    memberof: 'Phaser.Tilemaps.Tileset',
    type: { names: [Array] },
    readonly: true,
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 161,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 15 },
  { id: 'Phaser.Tilemaps.Tileset#getTileProperties',
    longname: 'Phaser.Tilemaps.Tileset#getTileProperties',
    name: 'getTileProperties',
    kind: 'function',
    scope: 'instance',
    description: 'Get a tiles properties that are stored in the Tileset. Returns null if tile index is not\ncontained in this Tileset. This is typically defined in Tiled under the Tileset editor.',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 173,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 16 },
  { id: 'Phaser.Tilemaps.Tileset#getTileData',
    longname: 'Phaser.Tilemaps.Tileset#getTileData',
    name: 'getTileData',
    kind: 'function',
    scope: 'instance',
    description: 'Get a tile\'s data that is stored in the Tileset. Returns null if tile index is not contained\nin this Tileset. This is typically defined in Tiled and will contain both Tileset collision\ninfo and terrain mapping.',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 191,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 17 },
  { id: 'Phaser.Tilemaps.Tileset#getTileCollisionGroup',
    longname: 'Phaser.Tilemaps.Tileset#getTileCollisionGroup',
    name: 'getTileCollisionGroup',
    kind: 'function',
    scope: 'instance',
    description: 'Get a tile\'s collision group that is stored in the Tileset. Returns null if tile index is not\ncontained in this Tileset. This is typically defined within Tiled\'s tileset collision editor.',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 210,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 18 },
  { id: 'Phaser.Tilemaps.Tileset#containsTileIndex',
    longname: 'Phaser.Tilemaps.Tileset#containsTileIndex',
    name: 'containsTileIndex',
    kind: 'function',
    scope: 'instance',
    description: 'Returns true if and only if this Tileset contains the given tile index.',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 228,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 19 },
  { id: 'Phaser.Tilemaps.Tileset#getTileTextureCoordinates',
    longname: 'Phaser.Tilemaps.Tileset#getTileTextureCoordinates',
    name: 'getTileTextureCoordinates',
    kind: 'function',
    scope: 'instance',
    description: 'Returns the texture coordinates (UV in pixels) in the Tileset image for the given tile index.\nReturns null if tile index is not contained in this Tileset.',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 246,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 20 },
  { id: 'Phaser.Tilemaps.Tileset#setImage',
    longname: 'Phaser.Tilemaps.Tileset#setImage',
    name: 'setImage',
    kind: 'function',
    scope: 'instance',
    description: 'Sets the image associated with this Tileset and updates the tile data (rows, columns, etc.).',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 265,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 21 },
  { id: 'Phaser.Tilemaps.Tileset#setTileSize',
    longname: 'Phaser.Tilemaps.Tileset#setTileSize',
    name: 'setTileSize',
    kind: 'function',
    scope: 'instance',
    description: 'Sets the tile width & height and updates the tile data (rows, columns, etc.).',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object], [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 284,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 22 },
  { id: 'Phaser.Tilemaps.Tileset#setSpacing',
    longname: 'Phaser.Tilemaps.Tileset#setSpacing',
    name: 'setSpacing',
    kind: 'function',
    scope: 'instance',
    description: 'Sets the tile margin & spacing and updates the tile data (rows, columns, etc.).',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object], [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 308,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 23 },
  { id: 'Phaser.Tilemaps.Tileset#updateTileData',
    longname: 'Phaser.Tilemaps.Tileset#updateTileData',
    name: 'updateTileData',
    kind: 'function',
    scope: 'instance',
    description: 'Updates tile texture coordinates and tileset data.',
    memberof: 'Phaser.Tilemaps.Tileset',
    params: [ [Object], [Object] ],
    returns: [ [Object] ],
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 332,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 24 },
  { id: 'Phaser.Tilemaps.Tileset',
    longname: 'Phaser.Tilemaps.Tileset',
    name: 'Tileset',
    kind: 'class',
    scope: 'static',
    description: 'A Tileset is a combination of an image containing the tiles and a container for data about\neach tile.',
    memberof: 'Phaser.Tilemaps',
    thisvalue: undefined,
    since: '3.0.0',
    meta:
     { lineno: 9,
       filename: 'Tileset.js',
       path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test' },
    order: 1 } 








 { filename: 'Angle.js',
     lineno: 7,
     columnno: 0,
     path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test\\phaser-src\\actions',
     code: {} },
  description: '[description]',
  kind: 'function',
  name: 'Angle',
  since: '3.0.0',
  params:
   [ { type: [Object],
       description: 'An array of Game Objects. The contents of this array are updated
by this Action.',
       name: 'items' },
     { type: [Object], description: '[description]', name: 'value' } ],
  returns:
   [ { type: [Object],
       description: 'The array of Game Objects that was passed to this Action.' } ],
  memberof: 'Phaser.Actions',
  longname: 'Phaser.Actions.Angle',
  scope: 'static' }
{ comment: '',
  meta:
   { range: [ 516, 658 ],
     filename: 'Angle.js',
     lineno: 18,
     columnno: 4,
     path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test\\phaser-src\\actions',
     code:
      { id: 'astnode100000003',
        name: 'Angle',
        type: 'FunctionExpression' },
     vars:
      { i: 'Angle~i',
        'items[undefined].angle': 'items[undefined].angle' } },
  undocumented: true,
  name: 'Angle',
  longname: 'Angle',
  kind: 'function',
  scope: 'global',
  params: [] }
{ comment: '',
  meta:
   { range: [ 563, 568 ],
     filename: 'Angle.js',
     lineno: 20,
     columnno: 13,
     path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test\\phaser-src\\actions',
     code: { id: 'astnode100000011', name:
'i', type: 'Literal', value: 0 } },
  undocumented: true,
  name: 'i',
  longname: 'Angle~i',
  kind: 'member',
  memberof: 'Angle',
  scope: 'inner',
  params: [] }
{ comment: '',
  meta:
   { range: [ 607, 630 ],
     filename: 'Angle.js',
     lineno: 22,
     columnno: 8,
     path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test\\phaser-src\\actions',
     code:
      { id: 'astnode100000023',
        name: 'items[undefined].angle',
        type: 'Identifier',
        value: 'value',
        paramnames: [] } },
  undocumented: true,
  name: 'angle',
  longname: 'items[undefined].angle',
  kind: 'member',
  memberof: 'items[undefined]',
  scope: 'static' }
{ comment: '',
  meta:
   { range: [ 661, 683 ],
     filename: 'Angle.js',
     lineno: 28,
     columnno: 0,
     path: 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test\\phaser-src\\actions',
     code:
      { id: 'astnode100000033',
        name: 'module.exports',
        type: 'Identifier',
        value: 'Angle',
        paramnames: [] } },
  undocumented: true,
  name: 'exports',
  longname: 'module.exports',
  kind: 'member',
  memberof: 'module',
  scope: 'static' }
{ kind: 'package',
  longname: 'package:undefined',
  files: [ 'C:\\Users\\Rou\\Desktop\\Dev2018\\Tests\\tsd-test\\phaser-src\\actions\\Angle.js' ] }